# Generated by Django 5.1.15 on 2026-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='category',
            field=models.CharField(choices=[('letters', 'Letters'), ('numbers', 'Numbers'), ('conversation', 'Conversation'), ('vocabulary', 'Vocabulary')], default='letters', max_length=20),
        ),
    ]
