# Generated by Django 5.1.15 on 2026-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_deck_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=10),
        ),
    ]
